# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovel.proto\"J\n\tFurniture\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x10\n\x08tempoUso\x18\x03 \x01(\x03\x12\x11\n\tdescricao\x18\x04 \x01(\t\"4\n\nCriarMovel\x12\x0b\n\x03\x63pf\x18\x01 \x01(\x03\x12\x19\n\x05movel\x18\x02 \x01(\x0b\x32\n.Furniture\"\x1b\n\x0c\x42uscarMoveis\x12\x0b\n\x03\x63pf\x18\x01 \x01(\x03\",\n\x0c\x45xcluirMovel\x12\x0f\n\x07idMovel\x18\x01 \x01(\x03\x12\x0b\n\x03\x63pf\x18\x02 \x01(\x03\"$\n\x12RespostaCriarMovel\x12\x0e\n\x06status\x18\x01 \x01(\x05\"&\n\x14RespostaExcluirMovel\x12\x0e\n\x06status\x18\x01 \x01(\x05\"2\n\x14RespostaBuscarMoveis\x12\x1a\n\x06moveis\x18\x01 \x03(\x0b\x32\n.Furniture2\xa9\x01\n\x05Movel\x12\x30\n\ncriarMovel\x12\x0b.CriarMovel\x1a\x13.RespostaCriarMovel\"\x00\x12\x36\n\x0c\x65xcluirMovel\x12\r.ExcluirMovel\x1a\x15.RespostaExcluirMovel\"\x00\x12\x36\n\x0c\x62uscarMoveis\x12\r.BuscarMoveis\x1a\x15.RespostaBuscarMoveis\"\x00\x62\x06proto3')



_FURNITURE = DESCRIPTOR.message_types_by_name['Furniture']
_CRIARMOVEL = DESCRIPTOR.message_types_by_name['CriarMovel']
_BUSCARMOVEIS = DESCRIPTOR.message_types_by_name['BuscarMoveis']
_EXCLUIRMOVEL = DESCRIPTOR.message_types_by_name['ExcluirMovel']
_RESPOSTACRIARMOVEL = DESCRIPTOR.message_types_by_name['RespostaCriarMovel']
_RESPOSTAEXCLUIRMOVEL = DESCRIPTOR.message_types_by_name['RespostaExcluirMovel']
_RESPOSTABUSCARMOVEIS = DESCRIPTOR.message_types_by_name['RespostaBuscarMoveis']
Furniture = _reflection.GeneratedProtocolMessageType('Furniture', (_message.Message,), {
  'DESCRIPTOR' : _FURNITURE,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:Furniture)
  })
_sym_db.RegisterMessage(Furniture)

CriarMovel = _reflection.GeneratedProtocolMessageType('CriarMovel', (_message.Message,), {
  'DESCRIPTOR' : _CRIARMOVEL,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:CriarMovel)
  })
_sym_db.RegisterMessage(CriarMovel)

BuscarMoveis = _reflection.GeneratedProtocolMessageType('BuscarMoveis', (_message.Message,), {
  'DESCRIPTOR' : _BUSCARMOVEIS,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:BuscarMoveis)
  })
_sym_db.RegisterMessage(BuscarMoveis)

ExcluirMovel = _reflection.GeneratedProtocolMessageType('ExcluirMovel', (_message.Message,), {
  'DESCRIPTOR' : _EXCLUIRMOVEL,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:ExcluirMovel)
  })
_sym_db.RegisterMessage(ExcluirMovel)

RespostaCriarMovel = _reflection.GeneratedProtocolMessageType('RespostaCriarMovel', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTACRIARMOVEL,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:RespostaCriarMovel)
  })
_sym_db.RegisterMessage(RespostaCriarMovel)

RespostaExcluirMovel = _reflection.GeneratedProtocolMessageType('RespostaExcluirMovel', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTAEXCLUIRMOVEL,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:RespostaExcluirMovel)
  })
_sym_db.RegisterMessage(RespostaExcluirMovel)

RespostaBuscarMoveis = _reflection.GeneratedProtocolMessageType('RespostaBuscarMoveis', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTABUSCARMOVEIS,
  '__module__' : 'movel_pb2'
  # @@protoc_insertion_point(class_scope:RespostaBuscarMoveis)
  })
_sym_db.RegisterMessage(RespostaBuscarMoveis)

_MOVEL = DESCRIPTOR.services_by_name['Movel']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FURNITURE._serialized_start=15
  _FURNITURE._serialized_end=89
  _CRIARMOVEL._serialized_start=91
  _CRIARMOVEL._serialized_end=143
  _BUSCARMOVEIS._serialized_start=145
  _BUSCARMOVEIS._serialized_end=172
  _EXCLUIRMOVEL._serialized_start=174
  _EXCLUIRMOVEL._serialized_end=218
  _RESPOSTACRIARMOVEL._serialized_start=220
  _RESPOSTACRIARMOVEL._serialized_end=256
  _RESPOSTAEXCLUIRMOVEL._serialized_start=258
  _RESPOSTAEXCLUIRMOVEL._serialized_end=296
  _RESPOSTABUSCARMOVEIS._serialized_start=298
  _RESPOSTABUSCARMOVEIS._serialized_end=348
  _MOVEL._serialized_start=351
  _MOVEL._serialized_end=520
# @@protoc_insertion_point(module_scope)
