# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\"+\n\rBuscarUsuario\x12\x0b\n\x03\x63pf\x18\x01 \x01(\x03\x12\r\n\x05senha\x18\x02 \x01(\t\"0\n\x04User\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\t\x12\x0b\n\x03\x63pf\x18\x03 \x01(\x03\"*\n\x18RespostaCadastrarUsuario\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x15\n\x13\x42uscarTodosUsuarios\"5\n\x1bRespostaBuscarTodosUsuarios\x12\x16\n\x07usuario\x18\x01 \x03(\x0b\x32\x05.User2\xad\x01\n\x07Usuario\x12 \n\x05login\x12\x0e.BuscarUsuario\x1a\x05.User\"\x00\x12H\n\x10getTodosUsuarios\x12\x14.BuscarTodosUsuarios\x1a\x1c.RespostaBuscarTodosUsuarios\"\x00\x12\x36\n\x10\x63\x61\x64\x61strarUsuario\x12\x05.User\x1a\x19.RespostaCadastrarUsuario\"\x00\x62\x06proto3')



_BUSCARUSUARIO = DESCRIPTOR.message_types_by_name['BuscarUsuario']
_USER = DESCRIPTOR.message_types_by_name['User']
_RESPOSTACADASTRARUSUARIO = DESCRIPTOR.message_types_by_name['RespostaCadastrarUsuario']
_BUSCARTODOSUSUARIOS = DESCRIPTOR.message_types_by_name['BuscarTodosUsuarios']
_RESPOSTABUSCARTODOSUSUARIOS = DESCRIPTOR.message_types_by_name['RespostaBuscarTodosUsuarios']
BuscarUsuario = _reflection.GeneratedProtocolMessageType('BuscarUsuario', (_message.Message,), {
  'DESCRIPTOR' : _BUSCARUSUARIO,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:BuscarUsuario)
  })
_sym_db.RegisterMessage(BuscarUsuario)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

RespostaCadastrarUsuario = _reflection.GeneratedProtocolMessageType('RespostaCadastrarUsuario', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTACADASTRARUSUARIO,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:RespostaCadastrarUsuario)
  })
_sym_db.RegisterMessage(RespostaCadastrarUsuario)

BuscarTodosUsuarios = _reflection.GeneratedProtocolMessageType('BuscarTodosUsuarios', (_message.Message,), {
  'DESCRIPTOR' : _BUSCARTODOSUSUARIOS,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:BuscarTodosUsuarios)
  })
_sym_db.RegisterMessage(BuscarTodosUsuarios)

RespostaBuscarTodosUsuarios = _reflection.GeneratedProtocolMessageType('RespostaBuscarTodosUsuarios', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTABUSCARTODOSUSUARIOS,
  '__module__' : 'usuario_pb2'
  # @@protoc_insertion_point(class_scope:RespostaBuscarTodosUsuarios)
  })
_sym_db.RegisterMessage(RespostaBuscarTodosUsuarios)

_USUARIO = DESCRIPTOR.services_by_name['Usuario']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUSCARUSUARIO._serialized_start=17
  _BUSCARUSUARIO._serialized_end=60
  _USER._serialized_start=62
  _USER._serialized_end=110
  _RESPOSTACADASTRARUSUARIO._serialized_start=112
  _RESPOSTACADASTRARUSUARIO._serialized_end=154
  _BUSCARTODOSUSUARIOS._serialized_start=156
  _BUSCARTODOSUSUARIOS._serialized_end=177
  _RESPOSTABUSCARTODOSUSUARIOS._serialized_start=179
  _RESPOSTABUSCARTODOSUSUARIOS._serialized_end=232
  _USUARIO._serialized_start=235
  _USUARIO._serialized_end=408
# @@protoc_insertion_point(module_scope)
